apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-local-k8s-sql
  namespace: my-local-k8s
spec:
  serviceName: my-local-k8s-sql-service
  selector:
    matchLabels:
      app: my-local-k8s-sql
  replicas: 1  
  template:
    metadata:
      labels:
        app: my-local-k8s-sql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: my-local-k8s-sql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433 
        env:
          - name: ACCEPT_EULA
            value: "Y"     
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-sa-password
                key: password
        volumeMounts:
            - mountPath: /var/opt/mssql
              name: data              
  volumeClaimTemplates:
    - metadata:
         name: data
         namespace: my-local-k8s
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
            
---               
apiVersion: v1
kind: Service
metadata:
  name: my-local-k8s-sql-service
  namespace: my-local-k8s
spec:
  selector:
    app: my-local-k8s-sql
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1434
      targetPort: 1433
      nodePort: 31433
      
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: sql-sa-password
  namespace: my-local-k8s
data:
  password: UGFzc0B3b3Jk